// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLLS9ahZwSbJ8zMKQSuWz7iDrEf8AA2Aw',
    appId: '1:292077426012:web:76d9f1339358718181dd99',
    messagingSenderId: '292077426012',
    projectId: 'fruits-634f1',
    authDomain: 'fruits-634f1.firebaseapp.com',
    storageBucket: 'fruits-634f1.firebasestorage.app',
    measurementId: 'G-L8FVW90JLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmIBfPPLPOqkEGuk0kv9B2MYEkugKWnk',
    appId: '1:292077426012:android:ba17697b5c65167a81dd99',
    messagingSenderId: '292077426012',
    projectId: 'fruits-634f1',
    storageBucket: 'fruits-634f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUmx1iv-W9TKeOOqEe55MHl1G7vP3Ybvc',
    appId: '1:292077426012:ios:da3fe21228e030a681dd99',
    messagingSenderId: '292077426012',
    projectId: 'fruits-634f1',
    storageBucket: 'fruits-634f1.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUmx1iv-W9TKeOOqEe55MHl1G7vP3Ybvc',
    appId: '1:292077426012:ios:da3fe21228e030a681dd99',
    messagingSenderId: '292077426012',
    projectId: 'fruits-634f1',
    storageBucket: 'fruits-634f1.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLLS9ahZwSbJ8zMKQSuWz7iDrEf8AA2Aw',
    appId: '1:292077426012:web:2384fdb767432b8a81dd99',
    messagingSenderId: '292077426012',
    projectId: 'fruits-634f1',
    authDomain: 'fruits-634f1.firebaseapp.com',
    storageBucket: 'fruits-634f1.firebasestorage.app',
    measurementId: 'G-WSMW5Z40JV',
  );
}
